### PR TITLE
Add segmentation notebook

### PR DESCRIPTION
**Pull request by EvgeniyS99**

### CODE REVIEW

**Review by HollowPrincess — CHANGES_REQUESTED** [review]
Overall looks pretty nice but the notebook needs some improvements.

First of all, think about code structure: cells order, combine some of them. Also, add empty lines between code logical parts - they make code more readable.

Secondly, rethink the text: sometimes it looks more like statements, than the complete text. Add details, conclusions from graphs, etc.

**Comment by AlexeyKozhevin** [comment]
<p>not <code>Batch<strong>f</strong>low</code> but <code>Batch<strong>F</strong>low</code>   </p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505173891'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EvgeniyS99** [comment]
<p>I couldn't find the 'barplot' or anything similar in the batchflow plot function . </p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505174030'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EvgeniyS99** [comment]
<p>Maybe you're right, but I want to plot the train/val losses per epoch on the one plot after the training, so I need to average them and save to additional lists. Also, if I use <code>M.model.loss_list</code>, I get the <strong>&lt;unknown_container&gt; </strong>title in the Notifier plot. </p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505174509'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EvgeniyS99** [comment]
<p>I think, there is no a need in plotting dataset images, since I plot them below within the batch construction.</p><p>Also, I think that that class imbalance without background can be assessed from the one histogram, and we don't have to plot one more hist. </p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505174005'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by HollowPrincess** [comment]
<p>Please, show me how it looks with batchflow plot in histogram mode.</p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505174030'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by HollowPrincess** [comment]
<p>Add title for the plot</p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505174030'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by SergeyTsimfer — APPROVED** [review]

**Comment by EvgeniyS99** [comment]
<p>Link to the image with&nbsp;batchflow plot in histogram mode: https://gyazo.com/adbbf3ecf0fb74ab5a253b60fe224ff1</p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1505174030'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by EvgeniyS99** [comment]
<p>Yes, cause I want <code>loss</code>as outputs, as well as <code>predictions</code>    </p>

---

 <a href='https://app.reviewnb.com/analysiscenter/batchflow/pull/688/discussion/#comment-1534533506'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
